version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    volumes:
      - './:/server-bun'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

networks:
  default:
    external: true
    name: node_postgres_network
